### ISSUE TITLE
zk_export.py - UnicodeDecodeError

### ISSUE THREAD

**Issue by d3r3ktm** [LucidWorks/fusion-upgrade-scripts#9]
Hi
I'm trying to upgrade fusion from 1.2.0 to 1.2.3.
Encountered decode error when I tried to export data from zookeeper.
May I know how can I resolve this?

-bash-4.1$ python zk_export.py optimusqa1:2181 zk_fusion.export
INFO:__main__:connecting to optimusqa1:2181
INFO:__main__:gathering data
Traceback (most recent call last):
  File "zk_export.py", line 82, in <module>
    json_str = convert_to_json()
  File "zk_export.py", line 47, in convert_to_json
    json_str = json.dumps(data, sort_keys=True, indent=2)
  File "/usr/local/python2.7/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/python2.7/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/python2.7/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/local/python2.7/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/local/python2.7/lib/python2.7/json/encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 14: invalid continuation byte

**Comment by kiranchitturi** [comment]
@d3r3ktm Can you change the line `json_str = json.dumps(data, sort_keys=True, indent=2)` in `zk_export.py` to `json_str = json.dumps(data, sort_keys=True, indent=2, ensure_ascii=False)` and run that step again ?

**Comment by d3r3ktm** [comment]
@kiranchitturi I made the change but still hit the decode error but with a different description.

-bash-4.1$ python zk_export.py optimusqa1:2181 zk_fusion.export
INFO:__main__:connecting to optimusqa1:2181
INFO:__main__:gathering data
Traceback (most recent call last):
  File "zk_export.py", line 83, in <module>
    json_str = convert_to_json()
  File "zk_export.py", line 48, in convert_to_json
    json_str = json.dumps(data, sort_keys=True, indent=2, ensure_ascii=False)
  File "/usr/local/python2.7/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/python2.7/lib/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 16: ordinal not in range(128)

**Comment by kiranchitturi** [comment]
The fix seems to be changing the line from `json.dumps(data, sort_keys=True, indent=2, ensure_ascii=False)` to `json.dumps(data, sort_keys=True, indent=2, encoding='latin1')`

**Comment by d3r3ktm** [comment]
Yes it did. Thank you for your help.
